### PR TITLE
Inhibit ThirdParty libraries warnings and refactor+modernize several classes

### PR DESCRIPTION
**Pull request by nevack**
This got a little out of control, change is prerry big.

Copy & paste and Drag & Drop works as intended with Apple Music, Finder and FileTreeOutline

### CODE REVIEW

**Comment by nevack** [comment]
@kode54 First commit is more like mechanical change.

**Comment by nevack** [comment]
I think I'll update PlaylistEntry as a following change.
Also it will be good to have PlaylistEntry's index fields to be NSInteger/NSUInteger instead of int to conform to Apple's APIs

**Comment by kode54** [comment]
Yeah, that sounds good so far. The PlaylistEntry change sounds fine too.

**Comment by kode54** [comment]
Wait, this is ready now? Has anything changed since I last commented?

**Comment by nevack** [comment]
> Wait, this is ready now? Has anything changed since I last commented?

No changes. I just thought you could mind merging patch of this size in one PR.

**Comment by kode54** [comment]
Looks okay, I'll have to build it later, though.

**Pull request merged**
