### PR TITLE
Output handling

### PR DESCRIPTION
**Pull request by JanX2**
This PR resolves (or maybe hacks around) an issue I have been having for a while on my main machine: it has a lot of audio hardware connected to it and, for some I have not been able to determine, audio device IDs have a tendency to change. 

This is not finished quality code, but it works for me. Would you please have a look so we can discuss what needs improving so it can be merged into mainline Cog?

Thanks!

### CODE REVIEW

**Comment by kode54** [comment]
I'm accepting this for now, it looks like it will work. I'll have to test later.

**Comment by kode54** [comment]
Thought I'd comment on this fix now that it's committed.

It failed to list my correct output device in the preferences upon first startup. It listed the first device in alphabetical order instead, but correctly output to the system default device.

**Comment by JanX2** [comment]
Interesting. I will look into that.

**Comment by JanX2** [comment]
I can reproduce this issue on one of my machines. Trouble is it’s old and slow (slow SSD) and it takes ages to install a Xcode 11.3.1.

**Pull request merged**
